// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://grcsxpvyyxmrzpplwwur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyY3N4cHZ5eXhtcnpwcGx3d3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2OTU0ODQsImV4cCI6MjA3ODI3MTQ4NH0.fFcWBE08C3XNoLnTB9YRvzhx90QRU1ww3vFcPGTR5kI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);